#!/usr/bin/python3 -u

import argparse

import prbg

argparser = argparse.ArgumentParser(description="Pseudorandom bytes generator. If no filename is provided, writes to the standard output.")

argparser.add_argument("seed", help="seed of the pseudorandom generator")
argparser.add_argument("size", help="number of bytes generated")
argparser.add_argument("filename", nargs="?", help="name of the destination file")

args = argparser.parse_args()

if args.filename:
    prbg.prbg_to_file(args.seed, args.size, args.filename)
else:
    prbg.prbg_to_stdout(args.seed, args.size)
