import pathlib
import random
import sys


# creates a bytearray of given size filled with a sequence of pseudorandom generated values based on the given seed
def prbg(seed, size):
    # initializes the pseudorandom generator with the given seed
    random.seed(seed)
    # generates and returns the bytearray
    return bytearray(random.getrandbits(8) for _ in range(0, int(size)))


# writes the generated bytearray to a file
def prbg_to_file(seed, size, filename):
    pathlib.Path(filename).write_bytes(prbg(seed, size))


# writes the generated bytearray to the standard output
def prbg_to_stdout(seed, size):
    sys.stdout.buffer.write(prbg(seed, size))
