#!/usr/bin/python3 -u

import argparse
import random


def pseudo_random_bytearray(seed, size):
    random.seed(seed)
    return bytearray(random.getrandbits(8) for _ in range(0, 1024 * 1024 * int(size)))


if __name__ == '__main__':
    argparser = argparse.ArgumentParser()

    argparser.add_argument("seed", nargs="?")
    argparser.add_argument("size", nargs="?")
    argparser.add_argument("output", nargs="?")

    args = argparser.parse_args()

    with open(args.output, "wb") as f:
        f.write(pseudo_random_bytearray(args.seed, args.size))
